name: Branch Drift Check

on:
  push:
    branches: [ main, development ]
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  drift:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check drift between main and development
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            try {
              const { data } = await github.rest.repos.compareCommits({
                owner,
                repo,
                base: 'main',
                head: 'development',
              });
              core.info(`ahead_by=${data.ahead_by}, behind_by=${data.behind_by}`);
              if (data.ahead_by !== 0 || data.behind_by !== 0) {
                core.setFailed(`Branch drift detected: main...development ahead=${data.ahead_by}, behind=${data.behind_by}`);
              } else {
                core.notice('Branches are in sync');
              }
            } catch (err) {
              core.setFailed(`Failed to compare branches: ${err.message}`);
            }
